name: streamlit-app
channels:
 - conda-forge
 - defaults
dependencies:
 - python=3.11.5
 - pip
 - pip:
    - streamlit
    - pillow
    - numpy
    - opencv-python-headless
    - seaborn
    - matplotlib
    - pandas
    - tensorflow
    - keras
    - scikit-image
    - scikit-learn
    - requests
    

    
